name: 'Terraform'

on:
  push: 
    branches: [ "" ]
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  id-token: 'write'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
    # checkout repository to github action runner
    - name: Checkout
      uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v2.0.0
      with:
        workload_identity_provider: 'projects/624433382152/locations/global/workloadIdentityPools/github-demo-pool-niketa/providers/github'
        service_account: 'github-actions-workload-federa@niketa.iam.gserviceaccount.com'

     # Terraform Init
    - name: Terraform Init
      run: |
        cd terraform-google-cloud-vpc-template
        terraform init

     # Terraform Validate
    - name: Terraform Validate
      run: |
        cd terraform-google-cloud-vpc-template
        terraform validate

    # Terraform Plan
    - name: Terraform Plan
      run: |
        cd terraform-google-cloud-vpc-template
        terraform plan -var-file=vpc.tfvars -var-file=subnet.tfvars -var-file=firewall.tfvars

    #  Terraform TFLint
    - name: Install TFLint
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | sudo bash

    #  Run TFLint
    - name: Run TFLint
      run: |
        tflint --config .tflint.hcl  # Optional: Use a custom TFLint configuration file
      
    - name: Wiz.io Security Scan
      env:
        WIZ_API_KEY: ${{ secrets.WIZ_API_KEY }}  # Store Wiz.io API Key as a secret
      run: |
        curl -sSL https://download.wiz.io/cli | sudo bash
        wiz scan terraform -d . --format json > wiz_scan_report.json
        cat wiz_scan_report.json  # Print the scan results to the log (optional)

   # Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false

  
